### ISSUE TITLE
Use of deprecated function

### ISSUE THREAD

**Issue by bitwombat** [felixbr/autocurry#1]
Brilliant library! Cleans up my code really nicely (was using toolz' "partial" before). Thanks for it.

Using Python 3.6, I'm getting this deprecation warning:

```
/app/lib/python3.6/site-packages/autocurry/__init__.py:20: 
DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use 
inspect.signature() or inspect.getfullargspec()
    arg_spec = getargspec(self.f)

```

**Comment by felixbr** [comment]
Oh wow, thank you for the kind words! 🙂

To be honest I didn't think anyone would use this library as functional programming in Python is somewhat cumbersome and unidiomatic.

I haven't been using Python myself for several years now, so it would be great if you could write a PR replacing the method as detailed in the warning. Python 2 is officially dead now (thank god) so we don't have to think about backwards compatibility anymore and the change should be easy enough.

In the meantime I will have to figure out how to publish this thing, as I'm not sure I have the credentials anymore. 😅
I'll write an update once I know more.

Cheers
~ Felix

edit: If you want to run the tests locally, you can install `tox` (`pip3 install tox`) and then just run `tox` in the project root directory.

**Comment by bitwombat** [comment]
I'm learning Haskell, so I get that FP in Python might not be idiomatic, but it does bring benefits. I *think*!

Here's what the `main` of a recent program I wrote looks like. It grabs a local newspaper's RSS feed and characterises the stories as either news or sports, printing out a text listing of titles with URLs so I can click on them in a daily email.

Oh, and it keeps track of articles it's already reported (ones I've already 'seen')

I have a good chance of understanding how this works in 6 months!

```
def main():
    URL = "http://www.portnews.com.au/rss.xml"

    articles = pipe(
        URL,
        (
            tell_user("Fetching feed...", id),
            fetch_feed,
            parse_feed,
            tell_user("Found {} articles in feed", len),
            hash_titles,
            remove_seen(have_seen()),
            tell_user("{} articles are new", len),
            tell_user("Fetching article bodies...", id),
            fetch_bodies(body_fetcher),
            classify(NB_classifier()),
            sort,
        ),
    )

    # Split the classified, sorted articles into two pipes
    print(format_as_text(articles))
    mark_as_seen()(articles)
```

This is actually on-topic, because the above code used to have "partial" throughout it, but thanks to autocurry, those are just GONE!

**Comment by felixbr** [comment]
That's a pretty cool example. Maybe I should steal it for the readme. 😅

Don't get me wrong, you don't have to convince me about FP one bit. I left Python for functional languages for a reason.

In any case, I added a testing pipeline (aka CI) to the repository. I'd be happy if you write a PR fixing the deprecation warning. If you don't know how this works I can walk you through. 🙂

**Comment by felixbr** [comment]
Hey, sorry this took so long! 😓

I finally got around to figuring out how publishing to PyPi works nowadays.

Anyway, here's the release:
https://github.com/felixbr/autocurry/releases/tag/v0.2.0
https://pypi.org/project/Autocurry/0.2.0/

Thanks for your help! I'm closing this issue now but if you need anything else don't hesitate to tell me 🙂

Cheers
